
server:
  port: 8080


spring:
  datasource: 
    url: jdbc:mysql://database-1.cnpbrncnsfqw.us-east-2.rds.amazonaws.com/bms
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
  